### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by dididy** [CodeSoom/project-react-1-dididy#1]
1. 이 앱을 언제 사용하나요?

  같은 프로젝트를 진행하는 사람끼리 비대면으로 짝 프로그래밍을 진행하거나 상호간의 코드리뷰를 할 경우 사용합니다.

2. 제약 조건은 무엇인가요?

  각 참여자가 동시에 같은 라인을 편집할 수 없습니다. 그 외의 라인들은 각자 편집 가능합니다. (Lock 기능)
  각 참여자가 어떤 파일에 있는지와 커서의 위치를 서로 식별할 수 있어야 합니다. (식별 기능)
  각 참여자는 카메라와 마이크, 채팅 기능(아마도 WebRTC활용..) 등을 이용하여 소통 할 수  있어야 합니다.
  ... <시간이 남는다면>
  리포지토리를 쉽게 클론해서 가져올 수 있어야 하며(아마도 GitHub API 이용..) 이를 위한 버튼을 크롬 extension으로 제작하여야 합니다.
  리뷰 과정의 대화를 STT를 이용해 저장하고  리플레이 기능을 통해 시간에 따라 짝프로그래밍 혹은 코드리뷰가 어떻게 진행되었는지 확인 가능해야 합니다.(아마 객체 형태로 다운로드 가능하게끔 제작하거나 서버에 업로드)

3. 구체적인 사례는 무엇인가요?

  동아리원들과 비대면으로 같은 코드를 보고 소통해야 할 때(어설픈 짝프로그래밍, 코드리뷰..) zoom을 이용한 화면공유는 너무 느리고 vscode liveshare를 사용하면 소통이 힘든 경험이 있어서 제작을 결심하게 되었습니다.

  웹 기반으로 제작된 해당 플랫폼을 이용하게 되면 접근성과 편의성이 향상된 환경에서 작업을 진행할 수 있을 것 입니다. zoom, teams, google meet 같은 추가적인 화상통화 플랫폼 없이 자체 플랫폼만으로 소통할 수 있습니다.
  
  또한 크롬 확장프로그램을 통해 GitHub 리포지토리 상에 추가적으로 생선된 버튼을 클릭하여 현재 리포지토리의 코드를 바로 클론받아 웹브라우저를 이용해 곧바로 작업을 진행할 수 있는 환경이 구성되게끔 할 것 입니다.

자동으로 상대방이 참여가능한 링크를 전달 할 수 있도록 클립보드에 해당 링크가 자동으로 복사하게 만들 것이므로 편의성이 극대화 될 것입니다.

4. 이번주에 구현 할 기능을 우선 순위대로 작성해 주세요.
- [x] 환경 설정: React, TEST 환경, Redux 및 패키지 설치 등
- [x] WebRTC 연동 작업 - 필요하다면 Backend 구성(아마 Node.js)
- [x] 스켈레톤 레이아웃 작업

**Comment by hannut91** [comment]
ㅎㅎ재밌을 것 같네요! 기능이 꽤 커보이는데 가장 간단한 것 부터 시작하면 좋을 것 같아요!
